export * from "./BuscarPage"
export * from "./ChatPage"
export * from "./HistorialPage"
export * from "./HomePage"
export * from "./HistorialPacientePage"
export * from "./DatoPage"
export * from "./SolicitudesPages"